### ISSUE TITLE
[UI Issue] : Dark mode not Working Properly

### ISSUE THREAD

**Issue by TartejBrothers** [bogodars/Portfolio#1]
# Issues: 
- There is no dark mode for the form.
![image](https://github.com/bogodars/Portfolio/assets/112921727/ad6d835b-f843-4f72-93c3-2b42c3c2887c)

# Improvements:
- Add this to css, this will fix the overflow-y white area.
```css
html {
      background-color: #17AA74; 
}
```
- Add this to fix overflow-x : 
```css
body{
      overflow-x: hidden;
}
```
- Add some space above the dark mode button, it is stuck to the navbar
![image](https://github.com/bogodars/Portfolio/assets/112921727/832df504-51af-426d-b9e7-85a566b6b1c8)
- The font is default and doesn't go with the website.
